import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { auth, db } from "@/lib/firebase";
import { useEffect, useState } from "react";
import { onAuthStateChanged } from "firebase/auth";
import { collection, getDocs } from "firebase/firestore";
import ShowRealtimeData from "@/components/ShowRealtimeData";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [user, setUser] = useState(null);
  const [data, setData] = useState([]);

  useEffect(() => {
    if (!auth) return; // ⛔ Cegah error saat SSR
    const unsubscribe = onAuthStateChanged(auth, (user) => {
      if (user) {
        setUser(user);
        // User is signed in, fetch data from Firestore
        const fetchData = async () => {
          const querySnapshot = await getDocs(collection(db, "your-collection-name"));
          const dataList = querySnapshot.docs.map((doc) => doc.data());
          setData(dataList);
        };

        fetchData();
      } else {
        setUser(null);
        setData([]);
      }
    });

    return () => unsubscribe();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Next.js!</h1>
        {user ? (
          <div>
            <p>Signed in as {user.email}</p>
            <ShowRealtimeData />
            {/* Render your data here */}
            <div>
              {data.map((item, index) => (
                <div key={index}>
                  {/* Replace with your data fields */}
                  <p>{JSON.stringify(item)}</p>
                </div>
              ))}
            </div>
          </div>
        ) : (
          <p>You are not signed in. Please sign in to see your data.</p>
        )}
      </main>
    </>
  );
}